blank_issues_enabled: false
contact_links:
  - name: Streamlit community support
    url: https://discuss.streamlit.io/
    about: Please ask and answer questions here.
  - name: Streamlit documentation
    url: https://docs.jeamlit.io/
    about: To learn more about how Streamlit works.
  - name: Jeamlit docs README
    url: https://github.com/jeamlit/docs/blob/main/README.md
    about: To learn how Jeamlit's documentation works.
